downstreams:
  twitch:
    baseUrl: "${TWITCH_BASE_URL}"
    clientId: "${TWITCH_CLIENT_ID}"
    clientSecret: "${TWITCH_CLIENT_SECRET}"
    grantType: "${TWITCH_GRANT_TYPE}"
  igdb:
    baseUrl: "${IGDB_BASE_URL}"

